### ISSUE TITLE
inheritance matcher breaks headers containing escaped quotes in the description of an info field

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/vip-inheritance-matcher#32]
Header in the input file:
```## INFO=<ID=TEST,Number=1,Type=Integer,Description="\"End position (for use with symbolic alleles)\"">```

```## INFO=<ID=TEST,Number=1,Type=Integer,Description="End position (for use with symbolic alleles)\">```

which is invalid due to the double quote not being closed

**Comment by dennishendriksen** [comment]
Fixed in https://github.com/molgenis/vip-inheritance-matcher/pull/33
